sudo: required
language: ruby
dist: xenial
rvm:
  - 2.5.6
before_script:
  - bundle exec rake db:create db:schema:load
  - mysql -u root -e "GRANT FILE ON *.* to root@127.0.0.1"
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - mysql -u root -e "SET GLOBAL time_zone = 'Australia/Sydney';"
script: bundle exec rake test:all
addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7
