sudo: required
language: ruby
dist: xenial
rvm:
  - 2.5.6
services:
  - mysql
before_script:
  - bundle exec rake db:create db:schema:load
  - mysql -u root -e "GRANT FILE ON *.* to travis@127.0.0.1"
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u travis mysql
  - mysql -u travis -e "SET GLOBAL time_zone = 'Australia/Sydney';"
script: bundle exec rake test
deploy:
  provider: script
  script:
    - sudo ./script/run-docker-builds.sh
  on:
    tags: true
