version: "3.7"
services:
 db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   ports:
      - "3307:3306"
 redis:
   image: "redis:4.0-alpine"
   command: redis-server
   volumes:
      - "redis:/data"

 web:
   depends_on:
      - "db"
      - "redis"
   build: .
   command: bundle exec rails s -p 3000 -b '0.0.0.0'

   ports:
      - "3000:3000"
   environment:
     DB_USERNAME: root
     DB_PASSWORD: root
     DB_DATABASE: sample
     DB_PORT: 3306
     DB_HOST: db
     RAILS_MAX_THREADS: 5
     REDIS_URL: "redis://redis:6379/12"
     RAILS_ENV: 'development'

   volumes:
      - ".:/app"

 sidekiq:
   depends_on:
      - "db"
      - "redis"
   build: .
   command: 'bundle exec sidekiq'
   volumes:
      - ".:/app"
   environment:
     REDIS_URL: redis://redis:6379/12
     RAILS_ENV: 'development'

volumes:
 redis:
 db:
