default: &default
 adapter: mysql2
 encoding: utf8mb4
 collation: utf8mb4_bin
 reconnect: false
 pool: 50
 username: <%= ENV['DB_USERNAME'] %>
 password: <%= ENV['DB_PASSWORD'] %>
 port: <%= ENV['DB_PORT'] %>
 host: <%= ENV['DB_HOST'] %>


development:
 <<: *default
 database: <%= ENV['DB_DATABASE'] %>_development

test:
  adapter: mysql2
  encoding: utf8
  username: root
  port: 3306
  host: 127.0.0.1
  database: rails_mysql_test
  
staging:
  <<: *default
  database: <% ENV['DB_DATABASE'] %>_staging

production:
 <<: *default
 database: <%= ENV['DB_DATABASE'] %>
