default: &default
 adapter: mysql2
 encoding: utf8mb4
 collation: utf8mb4_bin
 reconnect: false
 pool: 50
 username: root
 password: pariganaka6

development:
 <<: *default
 database: mysql_docker_development

production:
 <<: *default
 database: <%= ENV['DB_DATABASE'] %>
